#!/usr/bin/env sh
# Executa checagens antes de enviar o código para o repositório remoto

echo "Executando checagens de pre-push... (lint, test, build, coverage)"
npm run lint && npm run build && npm run test:cov